### ISSUE TITLE
Configure local network for remote work

### ISSUE THREAD

**Issue by tmralmeida** [lardemua/atlascar2#10]
- [x] Rename the network to something according
- [x] Setup a password for the network
- [x] Configure the ip forwarding in the pc and router

**Comment by miguelriemoliveira** [comment]
Me and @afonsocastro created a network called smc (since the router is called smc). No password. We connect with our laptop to this network using a cable (set a static ip in the range 192.168.2.2xx). Internet on the laptop is provided by eduroam.

The Atlascar2 server has ip in this network 192.168.2.102
