### ISSUE TITLE
Install odometer from Atlascar1 in Atlascar2

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atlascar2#36]
FYI @vitoruapt .

This is to discuss the possibility of installing the odometer in the atlascar2. @manuelgitgomes and @Sarxell  you said the screws are not compatible, right?

How difficult would it be to make a new interface?

**Comment by manuelgitgomes** [comment]
Yes! The old odometer is installed with the 5 screws seen on the right rim. The rim on the left, the one from AtlasCar2, only has 4 screw holes.
![image](https://user-images.githubusercontent.com/58152228/164814059-187cb00a-a952-41b9-b0a3-12552636cf9c.png)

I don't think a new interface would be very difficult, because the design would be the same as the one already on AtlasCar1, only changing the place of the screw holes.
The question is, is it worth it? 
With the new developments in #30, almost millimetric precision exists. Is the odometer more precise? And if so, is it worth the effort?

**Comment by miguelriemoliveira** [comment]
I am not entirely sure we will get what we need in #30, because @Sarxell reports problems with still measuring some rpms even when the car is stopped. I think it will be a noisy measurement.

To me the best approach would be to give @Sarxell some time to work ok #30 to see how far we can go. However, if we later on decide to advance with this installation of the odometer the machining of the interface could take weeks. Perhaps because of this we should right now start working on the interface design and send it to Eng. Festas ... 

Not really sure how to proceed, @vitoruapt, @manuelgitgomes  and @Sarxell ,what is your opinion?

**Comment by Sarxell** [comment]
I think that since I need to test with the GPS to see if it gives precise results, see the different driving modes and if they change something (like @vitoruapt  mentioned in #30) we need to be prepared for the worst which is the method in #30 being inaccurate. So thinking about the interface may be better, just to be prepared.

**Comment by manuelgitgomes** [comment]
I can try to design the interface. Do you have the model of the one in AtlasCar1?

**Comment by manuelgitgomes** [comment]
As stated in #39, here are the drawings:
[veio_rolamentos_draw.pdf](https://github.com/lardemua/atlascar2/files/8663616/veio_rolamentos_draw.pdf)
[new_wheel_supporter_draw.pdf](https://github.com/lardemua/atlascar2/files/8663617/new_wheel_supporter_draw.pdf)

**Comment by manuelgitgomes** [comment]
Hello! In talks with @vitoruapt and Eng. Heitor, we reached the conclusion that the previous design had the possibility of misaligning the shafts. To combat this, a flexible coupling should be added, like this one: 
![image](https://user-images.githubusercontent.com/58152228/167883416-bf83a4e3-12bf-4553-a9c7-7ce622cd03f0.png)
https://www.ptrobotics.com/material-impressao-3d/8359-acoplador-mecanico-flexivel-5x6x25mm-para-impressao-3d.html
This creates a more robust system and a more secure alignment of the shafts.
For this, these two pieces need remodelling, in order to accommodate the 25mm coupling device:
![image](https://user-images.githubusercontent.com/58152228/167884096-83cfda9f-31e2-47f1-adc8-5c3db567d9c5.png)
The drawings will follow in the next couple of hours.

**Comment by manuelgitgomes** [comment]
After a lot of thinking and searching, I don't think I have the needed measurements to have a fully functional drawing,
This is due to no normalization or documentation of most coupling mechanisms.  The ones who have are [really expensive](https://pt.farnell.com/huco/725-19-2020/coupling-5mm-x-5mm-aluminium/dp/7214741?st=flexible%20coupling).

![WhatsApp Image 2022-05-12 at 16 00 33](https://user-images.githubusercontent.com/58152228/168106270-47be54ae-dfd1-4f9b-834c-14c11d46b35d.jpeg)

Without knowing how much of the encoder shaft can fit inside the coupling (x on the previous figure), the displacement applied to the pieces shown below cannot be calculated. However, when that value is found, the modeling is trivial.

> For this, these two pieces need remodeling, in order to accommodate the 25mm coupling device:
> ![image](https://user-images.githubusercontent.com/58152228/167884096-83cfda9f-31e2-47f1-adc8-5c3db567d9c5.png)

So I believe we have two options. Order the affordable one and wait for the arrival to measure everything and then model everything, or order the expensive one and have already the measurements and send it to production ASAP.

Despite this, this part can be sent to production IMO:

[new_wheel_supporter_draw.pdf](https://github.com/lardemua/atlascar2/files/8680546/new_wheel_supporter_draw.pdf)

**Comment by vitoruapt** [comment]
It would be nice if the encoder could be left floating just attached by its shaft and the rotation of its case would be blocked by the cable through the passing hole... how feasible is that? We would not need any special fixation nor coupling device!
Check that possibility...
Anyway, the triangular part can be manufactured, of course.

**Comment by manuelgitgomes** [comment]
Good evening! Thank you for your opinion!


> Check that possibility...

Would that allow for a regular rotation? The main problem I'm thinking about is being misaligned with the wheel's axis. This creates a rotation that is "phased" to one side, i.e., it rotates faster in one half and slower in the other. Nevertheless, I can talk this out with Eng. Heitor tomorrow.



> Anyway, the triangular part can be manufactured, of course.

I will ask Eng. Festas tomorrow then!

**Comment by manuelgitgomes** [comment]
> I will ask Eng. Festas tomorrow then!

Part sent to production. On Tuesday/Wednesday should be manufactured.

**Comment by miguelriemoliveira** [comment]
Great. Thank you

**Comment by manuelgitgomes** [comment]
Hello to all!


> Check that possibility...

I have talked with Eng. Heitor and he said the encoder wires may be at stake with this solution.

Regarding the coupling possibility, the company Huco seems to be the best solution I found on the market. They have documentation and versatility. We have two options [[1]](https://www.huco.com/shop/couplings/beam-couplings/multi-beam-couplings/725-16) [[2]](https://www.huco.com/shop/couplings/beam-couplings/multi-beam-couplings/725-19) for a 5/6mm couplings. Their downside is their price and the fact the company is located in UK, making shipping complicated. However, the portuguese Farnell store has a [5/5mm Huco coupling in their store by 28 euros](https://pt.farnell.com/huco/725-19-2020/coupling-5mm-x-5mm-aluminium/dp/7214741?st=flexible%20coupling). I have talked with Eng. Festas and he said the adaption of a 5/5mm to 5/6mm is easy to manufacture. Because of that, I believe this is the best option, because I can design and draw the pieces with certainty of the measurements and end this process as soon as possible.

What do you think?

**Comment by vitoruapt** [comment]
> I have talked with Eng. Heitor and he said the encoder wires may be at stake with this solution.
And if you protect the cable with a small pipe to serve as a guide...? If this is the unique problem, I would still feel to keep trying the solution because it is the simplest one and no special mechanical coupling would be needed!
But if you feel more comfortable with the mechanical coupling solution, and parts are easy to purchase or manufacture, please do go ahead with it :-) !

**Comment by miguelriemoliveira** [comment]
From my side nothing to add, I agree with whatever you suggest ... (sorry)

**Comment by manuelgitgomes** [comment]
Ok prof @vitoruapt, tomorrow I will talk this out better with Eng. Heitor. The problem he presented was the twisting of the wires inside the outer protection. You are right, this is the easier solution.

**Comment by manuelgitgomes** [comment]
Hello! Eng. Heitor came up with some suggestions, to go alongside the one @vitoruapt came up with:

- Place some of the wire inside the "container", so in the case the wires break, we have some leeway to push some of the wire out and remove the damaged part;
- If the encoder has the tendency to touch the inside wall of the "container", we can line those walls with some sponge.

I think this might be the way to go. One problem is the new encoder's shaft does not have a face, making it necessary to mill the shaft to look like this:
![image](https://user-images.githubusercontent.com/58152228/168850633-2dd8e26f-ce09-4a34-b1e8-2611ec1d1972.png)

Tomorrow I will present this solution to Eng, Heitor and Eng. Festas. If that's ok, we can manufacture this:
[veio_rolamentos_draw.pdf](https://github.com/lardemua/atlascar2/files/8663616/veio_rolamentos_draw.pdf)

**Comment by vitoruapt** [comment]
OK. Seem all good solutions, except maybe milling the shaft face, but I am not an expert. In any case, alternative solutions do certainly exist and Eng. Festas will provide one if needed :-)
Let's see if manufacturing the new part can be done in a short term...

**Comment by manuelgitgomes** [comment]
Hello! The triangular part is manufactured:
![image](https://user-images.githubusercontent.com/58152228/169087283-30c8b3c9-e168-4b63-8e49-e46f3e437acc.png)
After talks with Eng. Heitor and Eng. Festas, the best solution to replace the milling of the shaft, we can install a plastic tube inside the existing part and tighten it with a stud. Currently, we have a tube that can fit inside the existing part but it is too narrow to fit the encoder's shaft inside it. Tomorrow, Eng. Heitor and I will enlarge the inside hole of the tube with a drill and see if this option is viable. If so, no further parts are needed to manufacture.
![image](https://user-images.githubusercontent.com/58152228/169089893-c06d0163-7f55-47a6-b22d-87fc3a1acd76.png)

**Comment by vitoruapt** [comment]
OK. How heavy is the triangular part? It looks sturdy but as it is symmetric, it should not interfere with the wheel balance when moving, which could create tire and general wearing at larger speeds! It may not be a relevant issue ;-)
Concerning the fixation of the encoder
Is it possible to fasten on the encoder side? Just to ensure that sliding does not occur, and that the system is easy to disassemble and reassemble every two years for the routine car inspection ;-)

**Comment by manuelgitgomes** [comment]
> OK. How heavy is the triangular part? It looks sturdy but as it is symmetric, it should not interfere with the wheel balance when moving, which could create tire and general wearing at larger speeds! It may not be a relevant issue ;-)


It's not that heavy!




> s it possible to fasten on the encoder side? Just to ensure that sliding does not occur, and that the system is easy to disassemble and reassemble every two years for the routine car inspection ;-)

I'm not sure I understood. The current stud is threaded, making it easier to disassemble if needed!

**Comment by manuelgitgomes** [comment]
Hello! The odometer is now installed! It misses a silcon filling for the wire, other than that, everything is mounted correctly.
 [IMG-20220523-WA0018.jpeg](https://user-images.githubusercontent.com/58152228/169856255-4a88cca9-3181-41fc-84a3-3feac60a73d5.jpeg)

We are having some issues but @Sarxell is describing them in #39

**Comment by miguelriemoliveira** [comment]
Nice work.

**Comment by manuelgitgomes** [comment]
Done
